# Generated by Django 6.0.5 on 2026-05-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('program_level', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('total_fee', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
