# Generated by Django 6.0.5 on 2026-05-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourse',
            name='total_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
